### ISSUE TITLE
QUESTION: How to make higher resolution properly

### ISSUE THREAD

**Issue by plant7403** [westgarthb/style-transfer-video-processor#2]
Hi, i'm very thankful for the developer of this project
i was looking for working video style transfer ai for many months, i was literally dying finding it
Thank you a lot ♥️

I have question about resolution, i have resources and time to make 1080p
But when i change frame height, it makes the style_ref images smaller on the result
Is there a way to keep the size of the pattern same as height 400, but make 1080 resolution, thank you 😃

**Comment by jogplus** [comment]
Hello, thank you for the kind words!

Regarding your question, after you changed the FRAME_HEIGHT in `config.py`, are you saying that the style_ref images are not scaling to match this new FRAME_HEIGHT? If so, this is by design, and you will need to scale the style_ref images manually using some other photo editing software. 

Additionally, if you have multiple style_ref images, they will all be scaled to match the dimensions of the first style_ref image and you will see: "WARNING: Resizing style images...". To avoid this, make sure all style_ref images are the same size.

**Comment by plant7403** [comment]
Thank you for your reply ✨
How should I scale the style_ref images? 
Just zoom, or zoom and better image quality, or how?
Thank you 🔥

**Comment by jogplus** [comment]
For best results you should try to use a style_ref image with a resolution that matches your FRAME_HEIGHT. However, if that's not possible, you could try using something like http://www.simpleimageresizer.com/ to stretch the style_ref image to match the new resolution.
